# Designed to keep develop branch as a perfect copy of LabKey fork
on:
  schedule:
    - cron:  "5 */3 * * *"
jobs:
  sync-release-branches:
    #See: https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    # github.head_ref should only be set on forked repos, meaning this action should only run on the primary fork
    if: github.head_ref == ""
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Release Branches"
        uses: bimberlabinternal/DevOps/githubActions/branch-create@master
        with:
          source_repo: "labkey/BimberLabKeyModules"
          source_branch_prefix: "release"
          destination_repo: "BimberLabInternal/BimberLabKeyModules"
          destination_branch_prefix: "discvr-"
          github_token: ${{ secrets.GITHUB_TOKEN }}
  sync-develop:
    if: github.head_ref == ""
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Develop Branch"
        uses: bimberlabinternal/DevOps/githubActions/git-sync@master
        with:
          source_repo: "labkey/BimberLabKeyModules"
          source_branch: "develop"
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
